[project]
name = "ai-cmd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "openai>=1.85.0",
]
[project.scripts]
ai = "cli.main:cli"
